### ISSUE TITLE
this needs to be added to the FAQ

### ISSUE THREAD

**Issue by ftrotter** [CareSet/COVID_Hospital_PUF#11]
Thank you for your interest in HHS Open Data. One note -- Patients should not be discouraged from seeking hospital care based on their interpretation of the data. Hospitals have protocols in place to keep patients safe from exposure and to ensure all patients are prioritized for care.
- HealthData.gov Team

**Comment by mikesisti** [comment]
Ready for merge.

**Comment by ftrotter** [comment]
missed this.. adding it now...
