### ISSUE TITLE
What does the term "inpatient" represent in the data?

### ISSUE THREAD

**Issue by melissa-ziedy** [CareSet/COVID_Hospital_PUF#17]
I'm trying to figure out what it means when the data dictionary references **inpatient** beds. Arizona's Department of Health has three types of beds: Inpatient (general population), ICU, and ED beds. 

Sometimes, the data dictionary clearly states whether or not ICU or ED beds are included in that field. Other times, it doesn't. What type of beds are used when the term "inpatient" is used.

For example, in the [Facility COVID PUF Community FAQ](https://github.com/CareSet/COVID_Hospital_PUF?src=hd), one of your recommended calculations is for _How full is the hospital with adult confirmed and suspected COVID patients_?

The formula is total_adult_patients_hospitalized_confirmed_and_suspected_covid_7_day_avg/ all_adult_hospital_inpatient_beds_7_day_avg. 

That takes -- 

**COL Q:** Average number of patients currently hospitalized in an adult **inpatient bed** who have laboratory-confirmed or suspected COVID19, including those in observation beds reported during the 7-day period. (No mention of ICU beds)

**Divided by** 

**COL N:** Average of total number of staffed inpatient adult beds in the hospital including all overflow and active surge/expansion beds used for inpatients (**including all designated ICU bed**s) reported during the 7-day period.

So if, ICU beds are not included whenever the term inpatient is used, then the above formula is flawed because Col Q doesn't include ICU beds. If ICU and ED beds are included anytime the inpatient term is used, then life just got a whole lot easier.

Thanks so much for your help in advance.

**Comment by ftrotter** [comment]
The semantics of the "bed" status are determined by the way that the hospitals read and interpret the reporting field FAQ AND potentially (when the states are intermediaries for reporting) the way that the state is defining these concepts. 

There is no strict enforcement of the semantics of these terms other than what is described in the documentation. 

Leaving this comment open because we would like more clarity here...
