### ISSUE TITLE
Adding reverse geo-encoders to the hospital dataset

### ISSUE THREAD

**Issue by skyprince999** [CareSet/COVID_Hospital_PUF#18]
While placekey information has been added for each dataset. 

Does it make sense to add a reverse geo-encoding to each hospital. Basically this will add Latitude & longitude information to the hospital dataset. This can help in identifying the hospital location and reaching out to them (??)

**Comment by ftrotter** [comment]
So the public CCN data that is linked to already has phone and address contact information. If the use case is "reaching out" I do not think lat and long is terribly relevant. 

The other complexity is that CCN only mostly translates to a single address. In many cases, one CCN includes events from multiple clinical locations. 

There is discussions about release a true facility-level dataset but there is no "true" facility-level identifier, which makes this problematic.
