### ISSUE TITLE
Tracking hospital-acquired covid transmission rates

### ISSUE THREAD

**Issue by BrianHHill** [CareSet/COVID_Hospital_PUF#19]
Posting this here after pickup over in [CoronaWhy community](https://coronawhy.slack.com/archives/C010CB7803Z/p1610548988164800), from a Chicago collaborator:

_"Good morning. I’m currently rotating in internal medicine at a hospital in Chicago that primarily serves an urban poor demographic. We are looking for info on hospital-acquired covid transmission rates across the country to standardize against."_

Within the CareSet data structures, how are facilities tracking hospital acquired transmission? Can they? At face glance, seems a simple enough question, but given the variables involved in an aerosolised virus/long asymptomatic incubation, would be difficult to work back through contact tracing and exposure events. Interested to hear if this is factored into dataset design, know the data model is likely evolving to support iatrogenic queries like this.

**Comment by ftrotter** [comment]
Just to be clear, this is not CareSet data, but data from the Feds.. we are just hosting the FAQ.

I do not know of any public data that tracks hospital-acquired COVID infections.. sadly. 

This is a good question.

Leaving this ticket open because I intend to see if we might request this data to be released...

**Comment by jsfenfen** [comment]
Hi @BrianHHill I believe that the variable "hospital_onset_covid" gets at what you are seeking in the *state level* aggregate file available [here](https://healthdata.gov/Hospital/COVID-19-Reported-Patient-Impact-and-Hospital-Capa/g62h-syeh ) It is intended to show folks who got COVID after being in the hospital for something else, though no idea how useful it is for your purposes.  `9. Total current inpatients with onset of suspected or laboratory-confirmed COVID-19 fourteen or more days after admission for a condition other than COVID-19 in this state.`

**Comment by BrianHHill** [comment]
Great, thanks for the pointer @jsfenfen - will be useful to understand how consistently this is used from state to state but at face glance, its a valid field, serves the purpose that was asked by our originating clinician.
