### ISSUE TITLE
Document errors in OR / WA suspected pediatric admissions, state aggregate files

### ISSUE THREAD

**Issue by jsfenfen** [CareSet/COVID_Hospital_PUF#24]
The `previous_day_admission_pediatric_covid_suspected` column in the state-aggregated version of the hospital file ("COVID-19 Reported Patient Impact and Hospital Capacity by State Timeseries", available [here](https://healthdata.gov/Hospital/COVID-19-Reported-Patient-Impact-and-Hospital-Capa/g62h-syeh) ) has an apparent error in Oregon and Washington state. See below, it appears that values after Oct. 19 are off. 

HHS was notified of this error Mar. 2 but has not been fixed as of today.

<img width="873" alt="image" src="https://user-images.githubusercontent.com/639012/111548603-327e7a00-8738-11eb-8cf9-a0f91b96ff4f.png">

**Comment by jsfenfen** [comment]
It looks like this has been fixed going forward, but there's still about 6 months of erroneous data. 
<img width="697" alt="image" src="https://user-images.githubusercontent.com/639012/112869076-9a568e00-9071-11eb-9386-180a4a84e62a.png">

http://www.jacobfenton.com/analyses/juvenile_covid_03012021/hhs.html#known-anomalies

**Comment by ftrotter** [comment]
I am closing this issue, but I am linking to it from the FAQ since it contains critical information
