### ISSUE TITLE
Readme nits

### ISSUE THREAD

**Issue by mikelehen** [CareSet/COVID_Hospital_PUF#3]
1. It includes a link to Chicago-specific dataset that you _probably_ didn't mean to highlight? https://healthdata.gov/dataset/covid-19-daily-cases-deaths-and-hospitalizations
2. There are some leftover TODOs at the very bottom.

**Comment by mikelehen** [comment]
That said, the readme is super helpful, thanks!

**Comment by ftrotter** [comment]
yep that is an error!! Working to fix it!
